name: "deploying artifacts to azure web app"
on:
  push:
  workflow_run:
    workflows: ["Building the .net application"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy: 
    name: Deploy to Web App
    runs-on: ubuntu-latest
    environment:
      name: webstore-prod

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webstore