name: Building the .net application
on: 
  workflow_dispatch:
  pull_request:
    branches: 
      - main 



jobs:
  build:
    name: 'Build and Publish .NET Web App'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3      

      - name: 'Restore'
        run: hello world