name: Building the .net application
on: 
  workflow_dispatch:
  pull_request:
    branches: 
      - main 



jobs:
  build:
    name: 'Build and Publish .NET Web App'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4      

      
      - name: 'Build'
        run: dotnet build --configuration Release

      - name: 'Publish'
        run: dotnet publish --configuration Release -o ./webstore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webstore
          path: ./webstore